import { User, GradeTable, Template } from './types';
import { v4 as uuidv4 } from 'uuid';

export const db = {
  users: [] as User[],
  gradeTables: [] as GradeTable[],
};

export const templates: Template[] = [
  {
    id: 'at-standard',
    name: 'Österreich – AHS/BHS Standard',
    description: 'Standardvorlage für österreichische Allgemein- und Berufsbildende Höhere Schulen',
    country: 'AT',
    isBlank: false,
    subjects: [
      { id: uuidv4(), name: 'Deutsch', shortName: 'D' },
      { id: uuidv4(), name: 'Englisch', shortName: 'E' },
      { id: uuidv4(), name: 'Mathematik', shortName: 'M' },
      { id: uuidv4(), name: 'Geschichte und Politische Bildung', shortName: 'GUP' },
      { id: uuidv4(), name: 'Geographie und Wirtschaftskunde', shortName: 'GWK' },
      { id: uuidv4(), name: 'Physik', shortName: 'PH' },
      { id: uuidv4(), name: 'Chemie', shortName: 'CH' },
      { id: uuidv4(), name: 'Biologie', shortName: 'BI' },
      { id: uuidv4(), name: 'Sport und Bewegung', shortName: 'SB' },
      { id: uuidv4(), name: 'Religion', shortName: 'REL' },
    ],
    sampleStudents: [
      { id: uuidv4(), firstName: 'Max', lastName: 'Mustermann', grades: {}, absences: { total: 0, unexcused: 0, behavior: 'SZ' } },
      { id: uuidv4(), firstName: 'Anna', lastName: 'Musterfrau', grades: {}, absences: { total: 0, unexcused: 0, behavior: 'SZ' } },
      { id: uuidv4(), firstName: 'Felix', lastName: 'Beispiel', grades: {}, absences: { total: 0, unexcused: 0, behavior: 'SZ' } },
    ],
  },
  {
    id: 'at-hif',
    name: 'Österreich – HTL/HIF Informatik',
    description: 'Vorlage für HTL/HIF Klassen mit Informatik-Schwerpunkt',
    country: 'AT',
    isBlank: false,
    subjects: [
      { id: uuidv4(), name: 'Deutsch', shortName: 'D' },
      { id: uuidv4(), name: 'Englisch', shortName: 'E' },
      { id: uuidv4(), name: 'Angewandte Mathematik', shortName: 'AM' },
      { id: uuidv4(), name: 'Naturwissenschaften', shortName: 'NW' },
      { id: uuidv4(), name: 'Computerarchitektur und Betriebssysteme', shortName: 'CAB' },
      { id: uuidv4(), name: 'Programmieren und Software Engineering', shortName: 'PSE' },
      { id: uuidv4(), name: 'Datenbanken und Informationssysteme', shortName: 'DBI' },
      { id: uuidv4(), name: 'Betriebswirtschaft und Management', shortName: 'BW' },
      { id: uuidv4(), name: 'Soziale und personale Kompetenz', shortName: 'SPK' },
      { id: uuidv4(), name: 'Vertiefendes Englisch', shortName: 'VE' },
      { id: uuidv4(), name: 'Bewegung und Sport', shortName: 'BS' },
      { id: uuidv4(), name: 'Religion', shortName: 'REL' },
    ],
    sampleStudents: [
      { id: uuidv4(), firstName: 'Bashkim', lastName: 'Agalliu', grades: {}, absences: { total: 67, unexcused: 56, behavior: 'SZ' } },
      { id: uuidv4(), firstName: 'Myron', lastName: 'Baranov', grades: {}, absences: { total: 33, unexcused: 0, behavior: 'SZ' } },
      { id: uuidv4(), firstName: 'Lena', lastName: 'Gruber', grades: {}, absences: { total: 10, unexcused: 2, behavior: 'SZ' } },
    ],
  },
  {
    id: 'de-gymnasium',
    name: 'Deutschland – Gymnasium',
    description: 'Standardvorlage für deutsche Gymnasien',
    country: 'DE',
    isBlank: false,
    subjects: [
      { id: uuidv4(), name: 'Deutsch', shortName: 'D' },
      { id: uuidv4(), name: 'Englisch', shortName: 'E' },
      { id: uuidv4(), name: 'Mathematik', shortName: 'M' },
      { id: uuidv4(), name: 'Geschichte', shortName: 'G' },
      { id: uuidv4(), name: 'Geographie', shortName: 'GEO' },
      { id: uuidv4(), name: 'Physik', shortName: 'PH' },
      { id: uuidv4(), name: 'Chemie', shortName: 'CH' },
      { id: uuidv4(), name: 'Biologie', shortName: 'BI' },
      { id: uuidv4(), name: 'Kunst', shortName: 'KU' },
      { id: uuidv4(), name: 'Musik', shortName: 'MU' },
      { id: uuidv4(), name: 'Sport', shortName: 'SP' },
      { id: uuidv4(), name: 'Religion/Ethik', shortName: 'REL' },
    ],
    sampleStudents: [
      { id: uuidv4(), firstName: 'Klaus', lastName: 'Müller', grades: {}, absences: { total: 0, unexcused: 0, behavior: '' } },
      { id: uuidv4(), firstName: 'Sabine', lastName: 'Schmidt', grades: {}, absences: { total: 0, unexcused: 0, behavior: '' } },
    ],
  },
  {
    id: 'ch-kantonsschule',
    name: 'Schweiz – Kantonsschule',
    description: 'Standardvorlage für Schweizer Kantonsschulen',
    country: 'CH',
    isBlank: false,
    subjects: [
      { id: uuidv4(), name: 'Deutsch', shortName: 'D' },
      { id: uuidv4(), name: 'Englisch', shortName: 'E' },
      { id: uuidv4(), name: 'Französisch', shortName: 'F' },
      { id: uuidv4(), name: 'Mathematik', shortName: 'M' },
      { id: uuidv4(), name: 'Geschichte', shortName: 'G' },
      { id: uuidv4(), name: 'Geographie', shortName: 'GEO' },
      { id: uuidv4(), name: 'Physik', shortName: 'PH' },
      { id: uuidv4(), name: 'Chemie', shortName: 'CH' },
      { id: uuidv4(), name: 'Biologie', shortName: 'BI' },
      { id: uuidv4(), name: 'Sport', shortName: 'SP' },
    ],
    sampleStudents: [
      { id: uuidv4(), firstName: 'Hans', lastName: 'Keller', grades: {}, absences: { total: 0, unexcused: 0, behavior: '' } },
      { id: uuidv4(), firstName: 'Maria', lastName: 'Huber', grades: {}, absences: { total: 0, unexcused: 0, behavior: '' } },
    ],
  },
  {
    id: 'blank',
    name: 'Leere Vorlage',
    description: 'Komplett leere Tabelle – eigene Fächer und Schüler hinzufügen',
    country: 'AT',
    isBlank: true,
    subjects: [],
    sampleStudents: [],
  },
];
